CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role = 'CANDIDATE')
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_skills_name UNIQUE (name)
);

CREATE TABLE candidate_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    seniority VARCHAR(255),
    desired_salary NUMERIC(12, 2),
    preferred_work_mode VARCHAR(255),
    professional_summary VARCHAR(2000),
    CONSTRAINT uk_candidate_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_candidate_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_candidate_profiles_seniority CHECK (seniority IN ('INTERN', 'JUNIOR', 'MID_LEVEL', 'SENIOR')),
    CONSTRAINT ck_candidate_profiles_work_mode CHECK (preferred_work_mode IN ('REMOTE', 'HYBRID', 'ONSITE'))
);

CREATE TABLE profile_skills (
    profile_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    CONSTRAINT pk_profile_skills PRIMARY KEY (profile_id, skill_id),
    CONSTRAINT fk_profile_skills_profile FOREIGN KEY (profile_id) REFERENCES candidate_profiles (id),
    CONSTRAINT fk_profile_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    seniority VARCHAR(255) NOT NULL,
    work_mode VARCHAR(255) NOT NULL,
    min_salary NUMERIC(12, 2) NOT NULL,
    max_salary NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_jobs_seniority CHECK (seniority IN ('INTERN', 'JUNIOR', 'MID_LEVEL', 'SENIOR')),
    CONSTRAINT ck_jobs_work_mode CHECK (work_mode IN ('REMOTE', 'HYBRID', 'ONSITE'))
);

CREATE TABLE job_skills (
    job_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    CONSTRAINT pk_job_skills PRIMARY KEY (job_id, skill_id),
    CONSTRAINT fk_job_skills_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_job_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (id)
);
